name: decimal
version: 2.3.3
description: >
  The decimal package allows you to deal with decimal numbers without losing
  precision.
repository: https://github.com/a14n/dart-decimal
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  rational: ^2.0.0

dev_dependencies:
  expector: ^0.1.2
  intl:
    git:
      url: https://github.com/dart-lang/i18n/
      ref: main
      path: pkgs/intl
  lints: ^2.0.0
  test: ^1.17.2
